version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ~/container/volumes/mongo-data:/data/db
    expose:
      - "27017"
  restful_api:
    image: book-library-api-dev
    ports:
      - "3245"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo/db_book
      - JWT_TOKEN=randomtoken88374622
volumes:
  mongo-data: